### ISSUE TITLE
force registration

### ISSUE THREAD

**Issue by goern** [whitel/vagrant-registration#25]
aka reregistration. In some situations it would be helpful to force a registration of a VM.

**Comment by humaton** [comment]
can you elaborate on this please? 

are you suggesting something like vagrant redhat-register <machine> ?

**Comment by goern** [comment]
ja, that is one way to implement it, or config.registration.always_force = true with the Vagrantfile. What I see is VMs with a subscription status of 'unknown' (that may be due to network problems or...) so I want that VM to execute the subscription again.

Second thing is unregistration, what it I remove a VM by hand (virt-manager), could Vagrant clean up all the registrations it has done in the past?
