### ISSUE TITLE
Destroy after halt does not clean up VM properly

### ISSUE THREAD

**Issue by whitel** [whitel/vagrant-registration#7]
I think this is related to the hooking, like the hook I want is not being triggered on "destroy only".

**Comment by strzibny** [comment]
Can you please elaborate?

For `halt->destroy` I get:

```
[strzibny@jstribnyntb testing]$ vagrant halt
==> default: Halting domain...
[strzibny@jstribnyntb testing]$ vagrant destroy
Guest-specific operations were attempted on a machine that is not
ready for guest communication. This should not happen and a bug
should be reported.
```

**Comment by whitel** [comment]
Well, that is a new one. I wonder if the other fixes may have made this problem worse (although, this is actually a more useful error). @humaton thoughts? In the past, the issue was that when you issued "destroy" it appear to succeed but the vm would not actually be removed.

**Comment by strzibny** [comment]
> The hook on destroy should only happen if the box has not been halted before (if it has, it has already been unreg'd). Or, it should test to see if the box is available for communication before trying to communicate.

Yep.

@humaton working on this one? or should I look?

**Comment by humaton** [comment]
@strzibny Feel free to take it I have different priorities right now

**Comment by strzibny** [comment]
So apparantly it wasn't problem of hooks. If you ask the machine on the `guest` Vagrant initialize the SSH connection, so if that fails, we just need to continue. PR submitted.
